// <auto-generated />
using System;
using CoreGym.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoreGym.Infrastructure.Migrations
{
    [DbContext(typeof(CoreGymDbContext))]
    [Migration("20260905165116_InitialSchemaGroups1And2")]
    partial class InitialSchemaGroups1And2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CoreGym.Domain.Entities.BodyMeasurement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<decimal?>("ArmsCm")
                        .HasColumnType("decimal(5,1)")
                        .HasColumnName("arms_cm");

                    b.Property<decimal?>("BodyFatPct")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("body_fat_pct");

                    b.Property<decimal?>("ChestCm")
                        .HasColumnType("decimal(5,1)")
                        .HasColumnName("chest_cm");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(SYSDATETIMEOFFSET())");

                    b.Property<decimal?>("HipsCm")
                        .HasColumnType("decimal(5,1)")
                        .HasColumnName("hips_cm");

                    b.Property<DateTime?>("MeasuredDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("measured_date")
                        .HasDefaultValueSql("(CAST(SYSUTCDATETIME() AS date))");

                    b.Property<decimal?>("MuscleMass")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("muscle_mass");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.Property<decimal?>("ThighsCm")
                        .HasColumnType("decimal(5,1)")
                        .HasColumnName("thighs_cm");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<decimal?>("WaistCm")
                        .HasColumnType("decimal(5,1)")
                        .HasColumnName("waist_cm");

                    b.Property<decimal?>("WeightKg")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("weight_kg");

                    b.HasKey("Id")
                        .HasName("PK_body_measurements");

                    b.HasIndex("UserId", "MeasuredDate")
                        .HasDatabaseName("IX_body_measurements_user_id_measured_date");

                    b.ToTable("body_measurements", (string)null);
                });

            modelBuilder.Entity("CoreGym.Domain.Entities.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(SYSDATETIMEOFFSET())");

                    b.Property<string>("Equipment")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("equipment");

                    b.Property<string>("GifUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("gif_url");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("image_url");

                    b.Property<string>("Instructions")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("instructions");

                    b.Property<string>("InstructionsAr")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("instructions_ar");

                    b.Property<string>("MuscleGroup")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("muscle_group");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("NameAr")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name_ar");

                    b.Property<string>("SecondaryMuscles")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("secondary_muscles");

                    b.Property<string>("Tips")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tips");

                    b.Property<string>("YoutubeVideoId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("youtube_video_id");

                    b.HasKey("Id")
                        .HasName("PK_exercises");

                    b.ToTable("exercises", null, t =>
                        {
                            t.HasCheckConstraint("CK_exercises_secondary_muscles_json", "[secondary_muscles] IS NULL OR ISJSON([secondary_muscles]) = 1");
                        });
                });

            modelBuilder.Entity("CoreGym.Domain.Entities.Food", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<decimal>("Calories")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("calories");

                    b.Property<decimal>("CarbsG")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(8,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("carbs_g");

                    b.Property<string>("Category")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("category")
                        .HasDefaultValueSql("(N'other')");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(SYSDATETIMEOFFSET())");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by");

                    b.Property<decimal>("FatG")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(8,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("fat_g");

                    b.Property<decimal>("FiberG")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(8,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("fiber_g");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsCustom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_custom");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("NameAr")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name_ar");

                    b.Property<decimal>("ProteinG")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(8,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("protein_g");

                    b.Property<decimal?>("ServingSize")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("serving_size")
                        .HasDefaultValueSql("((100))");

                    b.Property<string>("ServingUnit")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("serving_unit")
                        .HasDefaultValueSql("(N'g')");

                    b.HasKey("Id")
                        .HasName("PK_foods");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("IX_foods_created_by");

                    b.ToTable("foods", (string)null);
                });

            modelBuilder.Entity("CoreGym.Domain.Entities.Onboarding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("ActivityLevel")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("activity_level");

                    b.Property<int?>("Age")
                        .HasColumnType("int")
                        .HasColumnName("age");

                    b.Property<bool>("Completed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("completed");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(SYSDATETIMEOFFSET())");

                    b.Property<string>("Gender")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("gender");

                    b.Property<string>("Goal")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("goal");

                    b.Property<decimal?>("HeightCm")
                        .HasColumnType("decimal(5,1)")
                        .HasColumnName("height_cm");

                    b.Property<decimal?>("TargetWeight")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("target_weight");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(SYSDATETIMEOFFSET())");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<int?>("WeeklyWorkouts")
                        .HasColumnType("int")
                        .HasColumnName("weekly_workouts");

                    b.Property<decimal?>("WeightKg")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("weight_kg");

                    b.HasKey("Id")
                        .HasName("PK_onboarding");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_onboarding_user_id");

                    b.ToTable("onboarding", null, t =>
                        {
                            t.HasTrigger("trg_onboarding_updated_at");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("CoreGym.Domain.Entities.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int?>("Age")
                        .HasColumnType("int")
                        .HasColumnName("age");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("avatar_url");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(SYSDATETIMEOFFSET())");

                    b.Property<string>("Email")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)")
                        .HasColumnName("email")
                        .HasDefaultValueSql("(N'')");

                    b.Property<string>("FitnessGoal")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("fitness_goal");

                    b.Property<string>("FullName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("full_name");

                    b.Property<string>("Gender")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("gender");

                    b.Property<decimal?>("HeightCm")
                        .HasColumnType("decimal(5,1)")
                        .HasColumnName("height_cm");

                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name")
                        .HasDefaultValueSql("(N'')");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("role")
                        .HasDefaultValueSql("(N'client')");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(SYSDATETIMEOFFSET())");

                    b.Property<decimal?>("WeightKg")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("weight_kg");

                    b.HasKey("Id")
                        .HasName("PK_profiles");

                    b.ToTable("profiles", null, t =>
                        {
                            t.HasTrigger("trg_profiles_updated_at");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("CoreGym.Domain.Entities.ProgramDay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("DayNumber")
                        .HasColumnType("int")
                        .HasColumnName("day_number");

                    b.Property<string>("MuscleGroups")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("muscle_groups");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("NameAr")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name_ar");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.Property<Guid>("ProgramId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("program_id");

                    b.HasKey("Id")
                        .HasName("PK_program_days");

                    b.HasIndex("ProgramId")
                        .HasDatabaseName("IX_program_days_program_id");

                    b.ToTable("program_days", null, t =>
                        {
                            t.HasCheckConstraint("CK_program_days_muscle_groups_json", "[muscle_groups] IS NULL OR ISJSON([muscle_groups]) = 1");
                        });
                });

            modelBuilder.Entity("CoreGym.Domain.Entities.ProgramDayExercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid?>("ExerciseId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("exercise_id");

                    b.Property<bool>("IsMainLift")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_main_lift");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.Property<string>("NotesAr")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes_ar");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int")
                        .HasColumnName("order_index");

                    b.Property<Guid>("ProgramDayId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("program_day_id");

                    b.Property<int?>("RepsMax")
                        .HasColumnType("int")
                        .HasColumnName("reps_max");

                    b.Property<int?>("RepsMin")
                        .HasColumnType("int")
                        .HasColumnName("reps_min");

                    b.Property<int?>("RestSeconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("rest_seconds")
                        .HasDefaultValueSql("((90))");

                    b.Property<int?>("Sets")
                        .HasColumnType("int")
                        .HasColumnName("sets");

                    b.HasKey("Id")
                        .HasName("PK_program_day_exercises");

                    b.HasIndex("ExerciseId")
                        .HasDatabaseName("IX_program_day_exercises_exercise_id");

                    b.HasIndex("ProgramDayId", "OrderIndex")
                        .HasDatabaseName("IX_program_day_exercises_program_day_id_order_index");

                    b.ToTable("program_day_exercises", (string)null);
                });

            modelBuilder.Entity("CoreGym.Domain.Entities.TrainingProgram", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(SYSDATETIMEOFFSET())");

                    b.Property<int?>("DaysPerWeek")
                        .HasColumnType("int")
                        .HasColumnName("days_per_week");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("DescriptionAr")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description_ar");

                    b.Property<int?>("DurationWeeks")
                        .HasColumnType("int")
                        .HasColumnName("duration_weeks");

                    b.Property<string>("Goal")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("goal");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("is_active")
                        .HasDefaultValueSql("((1))");

                    b.Property<string>("Level")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("NameAr")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name_ar");

                    b.Property<string>("SplitType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("split_type");

                    b.HasKey("Id")
                        .HasName("PK_training_programs");

                    b.ToTable("training_programs", (string)null);
                });

            modelBuilder.Entity("CoreGym.Domain.Entities.UserGoal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(SYSDATETIMEOFFSET())");

                    b.Property<int?>("DailyCalories")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("daily_calories")
                        .HasDefaultValueSql("((2000))");

                    b.Property<int?>("DailyCarbsG")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("daily_carbs_g")
                        .HasDefaultValueSql("((250))");

                    b.Property<int?>("DailyFatG")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("daily_fat_g")
                        .HasDefaultValueSql("((65))");

                    b.Property<int?>("DailyProteinG")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("daily_protein_g")
                        .HasDefaultValueSql("((150))");

                    b.Property<decimal?>("DailySleepHours")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(4,2)")
                        .HasColumnName("daily_sleep_hours")
                        .HasDefaultValueSql("((8))");

                    b.Property<int?>("DailySteps")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("daily_steps")
                        .HasDefaultValueSql("((10000))");

                    b.Property<int?>("DailyWaterMl")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("daily_water_ml")
                        .HasDefaultValueSql("((2500))");

                    b.Property<decimal?>("TargetWeightKg")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("target_weight_kg");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(SYSDATETIMEOFFSET())");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<int?>("WeeklyWorkouts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("weekly_workouts")
                        .HasDefaultValueSql("((4))");

                    b.HasKey("Id")
                        .HasName("PK_user_goals");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_user_goals_user_id");

                    b.ToTable("user_goals", null, t =>
                        {
                            t.HasTrigger("trg_user_goals_updated_at");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("CoreGym.Domain.Entities.UserStreak", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<int>("CurrentStreak")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("current_streak")
                        .HasDefaultValueSql("((0))");

                    b.Property<int?>("FreezeAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("freeze_available")
                        .HasDefaultValueSql("((1))");

                    b.Property<DateTime?>("LastActiveDate")
                        .HasColumnType("date")
                        .HasColumnName("last_active_date");

                    b.Property<int>("LongestStreak")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("longest_streak")
                        .HasDefaultValueSql("((0))");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(SYSDATETIMEOFFSET())");

                    b.HasKey("UserId")
                        .HasName("PK_user_streaks");

                    b.ToTable("user_streaks", null, t =>
                        {
                            t.HasTrigger("trg_user_streaks_updated_at");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("CoreGym.Domain.Entities.BodyMeasurement", b =>
                {
                    b.HasOne("CoreGym.Domain.Entities.Profile", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_body_measurements_profiles");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CoreGym.Domain.Entities.Food", b =>
                {
                    b.HasOne("CoreGym.Domain.Entities.Profile", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_foods_profiles");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("CoreGym.Domain.Entities.Onboarding", b =>
                {
                    b.HasOne("CoreGym.Domain.Entities.Profile", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_onboarding_profiles");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CoreGym.Domain.Entities.ProgramDay", b =>
                {
                    b.HasOne("CoreGym.Domain.Entities.TrainingProgram", "Program")
                        .WithMany()
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_program_days_training_programs");

                    b.Navigation("Program");
                });

            modelBuilder.Entity("CoreGym.Domain.Entities.ProgramDayExercise", b =>
                {
                    b.HasOne("CoreGym.Domain.Entities.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_program_day_exercises_exercises");

                    b.HasOne("CoreGym.Domain.Entities.ProgramDay", "ProgramDay")
                        .WithMany()
                        .HasForeignKey("ProgramDayId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_program_day_exercises_program_days");

                    b.Navigation("Exercise");

                    b.Navigation("ProgramDay");
                });

            modelBuilder.Entity("CoreGym.Domain.Entities.UserGoal", b =>
                {
                    b.HasOne("CoreGym.Domain.Entities.Profile", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_user_goals_profiles");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CoreGym.Domain.Entities.UserStreak", b =>
                {
                    b.HasOne("CoreGym.Domain.Entities.Profile", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_user_streaks_profiles");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
